name: rengi_filim
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  flutter_native_splash: ^2.3.5
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  shimmer_pro: ^0.0.6
  http: ^1.1.0
  sqflite: ^2.0.0
  path: ^1.8.3
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/country_logo/
    - assets/images/logo/

  fonts:
    - family: UniSIRWAN_Adelle
      fonts:
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle Bold.ttf
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle ExtraBold.ttf
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle Heavy.ttf
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle Light.ttf
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle Regular.ttf
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle SemiBold.ttf
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle Thin.ttf
        - asset: assets/fonts/UniSIRWAN_Adelle/UniSIRWAN Adelle Ultrathin.ttf
